return {
  name = "filispeen/discord.lua",
  version = "REPLACE_ME", -- matches the latest release on GitHub, not the latest commit on main
  description = "Discord API wrapper written in Lua",
  tags = { "discord", "bot", "gateway", "luvit" },
  license = "MIT",
  author = { name = "filispeen" },
  homepage = "https://github.com/filispeen/discord.lua",
  dependencies = {
    "luvit/coro-http@3.2.4",
    "luvit/coro-websocket@3.1.1",
    "luvit/coro-net@3.3.1",
    "luvit/coro-channel@3.0.5",
    "luvit/coro-wrapper@3.1.0",
    "luvit/http-codec@3.0.8",
    "luvit/websocket-codec@3.0.3",
    "luvit/secure-socket@1.2.5",
    "luvit/resource@2.1.1",
    "luvit/base64@2.0.0",
    "luvit/sha1@1.0.4",
    "luvit/pathjoin@2.0.1",
    "luvit/los@2.0.2",
    "luvit/json@2.8",
  },
  files = {
    "init.lua",
    "lib/**.lua",
    "lib/**.dll",
    "README.md",
    "package.lua",
    "discord/**.lua",
  },
}
